version: "3"

services:
  backend:
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=$SERVER_URL
      - SWAGGER_HOST=$SWAGGER_HOST
      - MESSAGE_BASE_URL=$MESSAGE_BASE_URL
      - MESSAGE_API_KEY=$MESSAGE_API_KEY
      - OTP_TEMPLATED_ID=$OTP_TEMPLATED_ID
      - MESSAGE_SENDER=$MESSAGE_SENDER
      - JWT_ALGO=$JWT_ALGO
      - ALLOWED_ORIGINS=$ALLOWED_ORIGINS
      - JWT_EXPIRES_IN=$JWT_EXPIRES_IN
      - NETWORK_WEBHOOK_SECRET=$NETWORK_WEBHOOK_SECRET
      - JWT_ISSUER=$JWT_ISSUER
      - SQL_PORT=$SQL_PORT
      - SQL_USER=$SQL_USER
      - SQL_HOST=$SQL_HOST
      - TEST_MODE=$TEST_MODE
      - EMAIL_TEST_MODE=$EMAIL_TEST_MODE
      - SQL_DATABASE=$SQL_DATABASE
      - SQL_PASSWORD=$SQL_PASSWORD
      - FROM_EMAIL=$FROM_EMAIL
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - ALTER_TABLE=$ALTER_TABLE
      - SQL_LOG=$SQL_LOG
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - ENCRYPTION_KEY=$ENCRYPTION_KEY
      - ENCRYPTION_IV=$ENCRYPTION_IV
      - ENCRYPTION_ALGORITHM=$ENCRYPTION_ALGORITHM
      - SERVER_UI_URL=$SERVER_UI_URL
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - CLOUD_FRONT_PRIVATE_KEY=$CLOUD_FRONT_PRIVATE_KEY
      - SIGN_URL_EXPIRE_TIME_FOR_PROFILE_IMAGE=$SIGN_URL_EXPIRE_TIME_FOR_PROFILE_IMAGE
      - AWS_SMTP_USER=$AWS_SMTP_USER
      - AWS_SMTP_PASSWORD=$AWS_SMTP_PASSWORD
      - AWS_SMTP_DOMAIN=$AWS_SMTP_DOMAIN
      - AWS_SMTP_PORT=$AWS_SMTP_PORT
      - APP_TESTING_PHONE=$APP_TESTING_PHONE
      - APP_TESTING_OTP=$APP_TESTING_OTP
      - WORK_FLOW_SERVICE_BASE_URL=$WORK_FLOW_SERVICE_BASE_URL
      - WHATSAPP_APP_ID=$WHATSAPP_APP_ID
      - WHATSAPP_PHONE_NUMBER_ID=$WHATSAPP_PHONE_NUMBER_ID
      - WHATSAPP_API_VERSION=$WHATSAPP_API_VERSION
      - WHATSAPP_BASE_URL=$WHATSAPP_BASE_URL
      - WHATSAPP_ACCESS_TOKEN=$WHATSAPP_ACCESS_TOKEN
      - WHATSAPP_APP_SECRET=$WHATSAPP_APP_SECRET
      - FIREBASE_TYPE=$FIREBASE_TYPE
      - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - FIREBASE_PRIVATE_KEY_ID=$FIREBASE_PRIVATE_KEY_ID
      - FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
      - FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
      - FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID
      - FIREBASE_AUTH_URI=$FIREBASE_AUTH_URI
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$FIREBASE_AUTH_PROVIDER_X509_CERT_URL
      - FIREBASE_CLIENT_X509_CERT_URL=$FIREBASE_CLIENT_X509_CERT_URL
      - FIREBASE_DB_URL=$FIREBASE_DB_URL
      - API_ACCESS_TOKEN=$API_ACCESS_TOKEN

    volumes:
      - server_logs:/usr/src/app/logs
      - web_images:/usr/src/app/images

volumes:
  server_logs:
  web_images:
